Ft delete article 168948247
andela/codepirates-ah-frontend pull request #22
Opened 2019-10-22 12:32 UTC by salviosage

#### What does this PR do?

- delete article

#### Description of Task to be completed?

- user should delete his or her article

#### How should this be manually tested?

- by cloning this repo and then checkout to this branch you will find a delete button on the homepage 

#### Any background context you want to provide?

#### What are the relevant pivotal tracker stories?

- [#168948247](https://www.pivotaltracker.com/story/show/168948247)

#### Screenshots (if appropriate)
![image](https://user-images.githubusercontent.com/38810299/67285908-b2b79600-f4d8-11e9-89f4-425d6e01c8fb.png)
![image](https://user-images.githubusercontent.com/38810299/67285923-b77c4a00-f4d8-11e9-8f1d-33532eb2ae54.png)
![image](https://user-images.githubusercontent.com/38810299/67285926-bb0fd100-f4d8-11e9-96ff-fb454af6a624.png)
![image](https://user-images.githubusercontent.com/38810299/67285936-bfd48500-f4d8-11e9-8a08-857beb51bef3.png)

#### Questions:

2019-10-22 15:02 UTC, habinezadalvan reviewed
Great work. However, you have to rebase.

2019-10-22 15:17 UTC, minega25 requested changes
@salviosage Great work, Please attend to the included feedback

2019-10-22 15:17 UTC, minega25 commented on package.json
> +  "proxy": "http://localhost:3000",
What is the purpose of this line

2019-10-22 15:17 UTC, minega25 commented on src/api/apiUtil.test.js
> +    await handleError(error);
@salviosage Would you add what we are testing here. ie (`expext() to be ...`

2019-10-22 15:17 UTC, minega25 commented on src/components/common/button/Button.test.js
> +  it('should render Button', () => {
@salviosage Same case here.

2019-10-22 15:18 UTC, minega25 commented on package.json
> +  "proxy": "http://localhost:3000",
rebase. The PR title is also not following team's standard.

2019-10-30 15:32 UTC, Anguandia commented on src/api/apiUtil.js
> +  return data;
Good work! How would you see replacing the multiple return statements with a single return. Declare a variable to which to assign the desired return value of each condition, then return this variable after all checks; a thing like; let result;  if a; result = res-a, if b; result= res-b ....; return result. I think this will avert code quality issues with code climate

2019-10-30 15:35 UTC, Anguandia commented on src/api/userApi.js
> +export const postApi = async (method, url, data) => fetch(`${actionsTypes.BACKEND_URL}/api/${actionsTypes.VERSION}/${url}`, {
Just a thought, named imports would perhaps be more elegant than actionTypes.{name} repeatedly

2019-10-30 15:37 UTC, Anguandia commented on src/components/common/model/model.test.js
> +  it('should render Button', () => {
I don't see where you are testing the rendering of the button as the test case states

2019-11-05 09:16 UTC, habinezadalvan approved these changes
LGTM

2019-11-05 19:13 UTC, SokoPaulSokool requested changes

2019-11-05 19:13 UTC, SokoPaulSokool commented on src/components/moreAction/moreAction.test.js
> +// });
remove commented code

2019-11-05 19:13 UTC, SokoPaulSokool commented on src/components/moreAction/index.js
> +                <Popover.Title className="deleting" as="h3" onClick={handleShows}>Delete</Popover.Title>
When someone hovers on edit or delete the cursor should be pointer

2019-11-06 08:42 UTC, salviosage commented on src/components/moreAction/moreAction.test.js
> +// });
I have removed them

2019-11-06 09:48 UTC, minega25 approved these changes
LGTM.

2019-11-06 10:25 UTC, SokoPaulSokool approved these changes
Good work

2019-11-06 10:43 UTC, merged