#167313368 User should be able to like and dislike a comment.
andela/codepirates-ah-frontend pull request #25
Opened 2019-10-28 14:41 UTC by minega25

#### What does this PR do?
 User should be able to like and dislike a comment.
#### Description of Task to be completed?
I want to be able to like or dislike articles articles, both authored by me and those not authored by me. Lets get creative in how we visually represent this!
#### How should this be manually tested?
Navigate to articleCard component displayed anywhere on the site.
Like a specific article
Dislike a specific article
#### What are the relevant pivotal tracker stories?
[#167313368](https://www.pivotaltracker.com/story/show/167313368)

2019-10-30 15:23 UTC, Anguandia reviewed
Looks Good!

2019-10-30 15:23 UTC, Anguandia commented on src/components/common/articleCard/articleCardTextComponent/index.js
> +      </div>
Would you please throw more light on the hard-coded likes' value of 100?

2019-11-02 17:56 UTC, minega25 commented on src/components/common/articleCard/articleCardTextComponent/index.js
> +      </div>
Worked on this.

2019-11-04 07:16 UTC, salviosage approved these changes
LGTM

2019-11-05 08:07 UTC, SokoPaulSokool requested changes
Good job. Though the UI would look better if the clap and the dislike button were the same sizes and in the same horizontal line as the social media icons.

2019-11-05 08:11 UTC, SokoPaulSokool requested changes
The clap and dislike buttons should not appear if you are the author of the article

2019-11-05 14:29 UTC, minega25 commented
> The clap and dislike buttons should not appear if you are the author of the article

@SokoPaulSokool I have worked on both feedback.

2019-11-05 14:58 UTC, habinezadalvan approved these changes
LGTM

2019-11-05 18:58 UTC, merged