#167313366: commenting on an article.
andela/codepirates-ah-frontend pull request #27
Opened 2019-10-31 09:21 UTC by habinezadalvan

#### What does this PR do?
- Creates and read a comment on a particular article
#### Description of Task to be completed?
- Comment on an article 
- Read all comment of a particular article
#### How should this be manually tested?
- Clone the repo
- run **git checkout ft-comment-on-an-article-167313366**
- run **npm install**
- run **npm run devserver**
- Use postman
Method: POST
- url **http://localhost:3000/api/v1/comments/articleSlug**
- In the json form use {"body": "comment"}
#### Any background context you want to provide?
- React, redux
#### What are the relevant pivotal tracker stories?
[#167313366](https://www.pivotaltracker.com/story/show/167313366)
#### Screenshots (if appropriate)
<img width="390" alt="Screen Shot 2019-10-31 at 11 18 33" src="https://user-images.githubusercontent.com/45101716/67934348-694e0180-fbd0-11e9-93f2-ecc08247c029.png">
<img width="380" alt="Screen Shot 2019-10-31 at 11 17 55" src="https://user-images.githubusercontent.com/45101716/67934367-70750f80-fbd0-11e9-83e3-ee5dd9ecd215.png">

#### Questions:
none

2019-11-05 19:22 UTC, SokoPaulSokool requested changes

2019-11-05 19:22 UTC, SokoPaulSokool commented on src/redux/actions/actionTypes.js
> +export const BACKEND_URL = 'http://localhost:3000';
put back the backend url.

2019-11-06 10:14 UTC, habinezadalvan commented on src/redux/actions/actionTypes.js
> +export const BACKEND_URL = 'http://localhost:3000';
I worked on that.

2019-11-06 11:07 UTC, SokoPaulSokool requested changes

2019-11-06 11:07 UTC, SokoPaulSokool commented on src/components/commentArticle/LikeDislikeReplies/LikeDislikeReplies.test.js
> +// import mockedStore from '../../../__mocks__/store';
Commented code

2019-11-06 11:07 UTC, SokoPaulSokool commented on src/components/commentArticle/commentCard/commentCard.test.js
> +    // button.simulate('click', {});
commented code

2019-11-06 11:07 UTC, SokoPaulSokool commented on src/components/commentArticle/commentTextArea/commentTextArea.scss
> +    // border: 1px solid rgba(0, 0, 0, 0.2);
commented code

2019-11-06 11:16 UTC, habinezadalvan commented on src/components/commentArticle/commentTextArea/commentTextArea.scss
> +    // border: 1px solid rgba(0, 0, 0, 0.2);
I removed them.

2019-11-06 11:16 UTC, habinezadalvan commented on src/components/commentArticle/commentCard/commentCard.test.js
> +    // button.simulate('click', {});
I removed them

2019-11-06 11:16 UTC, habinezadalvan commented on src/components/commentArticle/LikeDislikeReplies/LikeDislikeReplies.test.js
> +// import mockedStore from '../../../__mocks__/store';
I removed them

2019-11-06 11:20 UTC, merged